# Lineární algebra

## Gauss - Pivoting

In [1]:
import numpy as np

#Gaussova eliminační metoda
#----------------------------------------------------------------------
#https://www.youtube.com/watch?v=gAmMxdI0EKs&ab_channel=StudySession <- zdroj

#Tady definuju matice!

#matice A
A = np.array([
    [0, 8, 1],
    [1, 0, 1],
    [3, 2, 0]])

#výsledný vektor b
b = np.array([2,3,4])

"""
print(f"b.shape[0]: {b.shape[0]}")
print(f"pocet sloupcu b: {len(b.shape)}")
print(f"A.shape[0]: {A.shape[0]}")
"""


def Gaussovka(A, b):
    # Vstupní podmínka - zda je matice čtvercová!
    if A.shape[0] != A.shape[1]: # n=m?
        print("Matice není čtvercová!")
        return
    else:
        print("Matice je čtvercová!")

    if len(b.shape) != 1 or b.shape[0] != A.shape[0]: # Kontrola vektoru b
        print(f"b - pocet řádků: {b.shape[0]}")
        print(f"b - pocet sloupcu: {len(b.shape)}")
        print(f"A - počet řádků: {A.shape[0]}")
        print("Vektor je chybný, zkontroluj vstup!")
        return
    else:
        print("Matice je OK!")
        print("########\nInicializace iteračních proměnných")

        n = len(b)
        m = n - 1
        i = 0
        j = i - 1
        x = np.zeros(n)

        print("########\nSpojení matice A s vektorem b:")
        spojenaMatice = np.concatenate((A, b.reshape(-1, 1)), axis=1, dtype=float) # reshape - b.reshape(-1, 1) is used to reshape 1D do 2D, z vertikálně na svisle!
        print(f"\n{spojenaMatice}\n")

        # Gaussovka
        # pivoting - kontrola, jestli neni dělení 0
        while i < n:
            if spojenaMatice[i][i] == 0.0:
                print("Provádím pivoting...")
                max_index = np.argmax(np.abs(spojenaMatice[i:, i])) + i # hledáme největší prvek ve sloupci
                spojenaMatice[[i, max_index]] = spojenaMatice[[max_index, i]] # prohození řádků
                print(f"Prohození řádku {i} s řádkem {max_index}")
                print(f"Iterace:\n{spojenaMatice}\n")

            for j in range(i + 1, n):
                factor = spojenaMatice[j][i] / spojenaMatice[i][i]
                spojenaMatice[j] = spojenaMatice[j] - (factor * spojenaMatice[i])
                print(f"Iterace:\n{spojenaMatice}\n")

            i += 1 # zvyšuju {i} při průchodu kvůli podmínce

        # Zpátečné složení matice:
        x[m] = spojenaMatice[m][n] / spojenaMatice[m][m]

        for k in range(n - 2, -1, -1): # slouží pro zpětnou iteraci s polem!
            x[k] = spojenaMatice[k][n]

            for j in range(k + 1, n):
                x[k] -= spojenaMatice[k][j] * x[j]
            x[k] = x[k] / spojenaMatice[k][k]

        print("Výsledně hodnoty k proměnným x:\n")
        for c_vysledek in range(n):
            print(f"x{c_vysledek}....{x[c_vysledek]}")

        y = np.dot(A, x)  # výpočet hodnot y

        return x,y # vracím výsledky


x_res, y = Gaussovka(A, b)
print(f"\nVýsledné x:\n{x_res}")
print(f"Vypočtené y (A * x):\n{y}")

# Řešení soustavy rovnic Build-In - kontrola
solution = np.linalg.solve(A, b)

print("\nSolution numpy.linalg.solve():", solution)
print(np.dot(A,solution))

#Pro následnou interpolaci - zipnout, seřadit, interpolovat!

Matice je čtvercová!
Matice je OK!
########
Inicializace iteračních proměnných
########
Spojení matice A s vektorem b:

[[0. 8. 1. 2.]
 [1. 0. 1. 3.]
 [3. 2. 0. 4.]]

Provádím pivoting...
Prohození řádku 0 s řádkem 2
Iterace:
[[3. 2. 0. 4.]
 [1. 0. 1. 3.]
 [0. 8. 1. 2.]]

Iterace:
[[ 3.          2.          0.          4.        ]
 [ 0.         -0.66666667  1.          1.66666667]
 [ 0.          8.          1.          2.        ]]

Iterace:
[[ 3.          2.          0.          4.        ]
 [ 0.         -0.66666667  1.          1.66666667]
 [ 0.          8.          1.          2.        ]]

Iterace:
[[ 3.          2.          0.          4.        ]
 [ 0.         -0.66666667  1.          1.66666667]
 [ 0.          0.         13.         22.        ]]

Výsledně hodnoty k proměnným x:

x0....1.3076923076923077
x1....0.038461538461538325
x2....1.6923076923076923

Výsledné x:
[1.30769231 0.03846154 1.69230769]
Vypočtené y (A * x):
[2. 3. 4.]

Solution numpy.linalg.solve(): [1.30769231 0

## Gauss - bez pivotingu

In [2]:
import numpy as np

#Gaussova eliminační metoda
#----------------------------------------------------------------------
#https://www.youtube.com/watch?v=gAmMxdI0EKs&ab_channel=StudySession <- zdroj

#Tady definuju matice!

#matice A
A = np.array([
    [0, 8, 1],
    [1, 0, 1],
    [3, 2, 0]])

#výsledný vektor b
b = np.array([2,3,4])

"""
print(f"b.shape[0]: {b.shape[0]}")
print(f"pocet sloupcu b: {len(b.shape)}")
print(f"A.shape[0]: {A.shape[0]}")
"""

def Gaussovka(A, b):
    #Vstupní podmínka - zda je matice čtvercová!
    if A.shape[0] != A.shape[1]: #n=m?
        print("Matice není čtvercová!")
        return

    else:
        print("Matice je čtvercová!")

    if len(b.shape) != 1 or b.shape[0] != A.shape[0]: #Kontrola vektoru b
        print(f"b - pocet řádků: {b.shape[0]}")
        print(f"b - pocet sloupcu: {len(b.shape)}")
        print(f"A - počet řádků: {A.shape[0]}")
        print("Vektor je chybný, zkontroluj vstup!")
        return

    else:
        print("Matice je OK!")
        print("########\nInicializace iteračních proměnných")

        n = len(b)
        m = n-1
        i = 0
        j = i -1
        x = np.zeros(n)

        print("########\nSpojení matice A s vektorem b:")
        spojenaMatice = np.concatenate((A,b.reshape(-1, 1)), axis=1, dtype=float) #reshape - b.reshape(-1, 1) is used to reshape 1D do 2D, z vertikálně na svisle!
        print(f"\n{spojenaMatice}\n")

        #Gaussovka
            #pivoting - kontrola, jestli neni 0 na diag
        while i < n:
            if spojenaMatice[i][i] == 0.0:
                print("Nula! Budu dělit nulou!")
                return

            for j in range(i+1,n):
                factor = spojenaMatice[j][i] / spojenaMatice[i][i]
                spojenaMatice[j] = spojenaMatice[j] - (factor*spojenaMatice[i])
                print(f"Iterace:\n {spojenaMatice}\n")

            i += 1 #zvyšuju {i} při průchodu kvůli podmínce

        #Zpátečné složení matice:
        x[m] = spojenaMatice[m][n] / spojenaMatice[m][m]

        for k in range(n-2, -1, -1): #slouží pro zpětnou iteraci s polem!
            x[k] = spojenaMatice[k][n]

            for j in range(k + 1, n):
                x[k] -= spojenaMatice[k][j] * x[j]
            x[k] = x[k] / spojenaMatice[k][k]

        print("Výsledně hodnoty k proměnným x:\n")
        for c_vysledek in range(n):
            print(f"x{c_vysledek}....{x[c_vysledek]}")

Gaussovka(A,b)

# Řešení soustavy rovnic Build-In
solution = np.linalg.solve(A, b)

print("\nSolution numpy.linalg.solve():", solution)

Matice je čtvercová!
Matice je OK!
########
Inicializace iteračních proměnných
########
Spojení matice A s vektorem b:

[[0. 8. 1. 2.]
 [1. 0. 1. 3.]
 [3. 2. 0. 4.]]

Nula! Budu dělit nulou!

Solution numpy.linalg.solve(): [1.30769231 0.03846154 1.69230769]


## Jacobi, Gauss-Seidel

In [3]:
import numpy as np

# Nepřímá metoda - Gauss-Seidel, Jacobi
# https://cs.wikipedia.org/wiki/Jacobiho_metoda

A = np.array([
    [2, 1],
    [5, 7]
])
b = np.array([11, 13])


def jacobi(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    D = np.diag(A)
    print(f"Diagonála D:\n {D}")

    L = np.tril(A, k = -1)
    print(f"Dolní troj. L:\n {L}")

    U = np.triu(A, k = 1)
    print(f"Horní troj. U:\n {U}")

    for i in range(niteraci):
        x = (b - np.matmul((L + U),x))/D # np.matmul -> násobení
        print("iterace:",i, "x=",x)
    return x


x = jacobi(A, b, 20)

solution = np.linalg.solve(A, b)

print("reseni: ", x)
print("\nSolution numpy.linalg.solve():", solution)

Diagonála D:
 [2 7]
Dolní troj. L:
 [[0 0]
 [5 0]]
Horní troj. U:
 [[0 1]
 [0 0]]
iterace: 0 x= [5.         1.14285714]
iterace: 1 x= [ 4.92857143 -1.71428571]
iterace: 2 x= [ 6.35714286 -1.66326531]
iterace: 3 x= [ 6.33163265 -2.68367347]
iterace: 4 x= [ 6.84183673 -2.6654519 ]
iterace: 5 x= [ 6.83272595 -3.02988338]
iterace: 6 x= [ 7.01494169 -3.02337568]
iterace: 7 x= [ 7.01168784 -3.15352978]
iterace: 8 x= [ 7.07676489 -3.1512056 ]
iterace: 9 x= [ 7.0756028  -3.19768921]
iterace: 10 x= [ 7.0988446  -3.19685914]
iterace: 11 x= [ 7.09842957 -3.21346043]
iterace: 12 x= [ 7.10673022 -3.21316398]
iterace: 13 x= [ 7.10658199 -3.21909301]
iterace: 14 x= [ 7.10954651 -3.21898714]
iterace: 15 x= [ 7.10949357 -3.22110465]
iterace: 16 x= [ 7.11055232 -3.22106683]
iterace: 17 x= [ 7.11053342 -3.22182309]
iterace: 18 x= [ 7.11091154 -3.22180958]
iterace: 19 x= [ 7.11090479 -3.22207967]
reseni:  [ 7.11090479 -3.22207967]

Solution numpy.linalg.solve(): [ 7.11111111 -3.22222222]
